### ISSUE TITLE
Style errors on FileSet edit page.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1649]
> the permission form's lease and embargo selectors are overrunning the text

Moved this issue from  #1604

**Comment by atz** [comment]
Example:
![screen shot 2016-03-29 at 12 00 47 pm](https://cloud.githubusercontent.com/assets/109954/14120073/2219d9d0-f5a6-11e5-93a9-b117902880ac.png)

**Comment by atz** [comment]
One of these overlaps comes from http://localhost:3000/assets/curation_concerns.self-4e4167184078d8e858eee542cdad2883700618fc5d8b5e68b33e416fd0f926f9.css?body=1 (line 9477)
```css
access-controls .form-inline label {
    padding-left: 0;
    display: inline;
}
```
Removing the CC `padding-left` reinstates the Sufia padding.   Due to #1680, perhaps the answer is to stop including CurationConcern's CSS?
