### ISSUE TITLE
Batch upload sidebar title problem - untranslated key

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#2064]
http://localhost:3000/batch_uploads/new

- Sidebar title is "Header" (untranslated key)

![screen shot 2016-05-19 at 6 38 44 pm](https://cloud.githubusercontent.com/assets/109954/15414593/f3e1d766-1df0-11e6-93ac-76833547b0ce.png)

Similar format issues for file upload page.

**Comment by atz** [comment]
Inspecting this, we see again #1680, in that the problematic CSS is delivered 3 times over: 
```css
.radio input[type="radio"], .radio-inline input[type="radio"], .checkbox input[type="checkbox"], .checkbox-inline input[type="checkbox"] {
    position: absolute;
    margin-left: -20px;
    margin-top: 4px \9;
}
.radio input[type="radio"], .radio-inline input[type="radio"], .checkbox input[type="checkbox"], .checkbox-inline input[type="checkbox"] {
    position: absolute;
    margin-left: -20px;
    margin-top: 4px \9;
}
.radio input[type="radio"], .radio-inline input[type="radio"], .checkbox input[type="checkbox"], .checkbox-inline input[type="checkbox"] {
    position: absolute;
    margin-left: -20px;
    margin-top: 4px \9;
}
```
